Sandmann79/xbmc

- plugin.video.amazon-test/default.py
- plugin.video.amazon/resources/lib/appfeed.py
On an Android box with Kodi 16, both plugins would immediately jump back to the main menu after displaying search results. This commit removes the close actions at the end of the search function.
Fixes #16.
> Fixed search problems on both plugins

- plugin.video.amazon-test/default.py
- plugin.video.amazon/resources/lib/common.py
As reported in #88 the python version checks in 39b12597e5845e3b1dfe1f85d9bdfe92900ca603 introduced a bug where previously working environments stopped completely. I changed the raw python version check and targeted the problems with exception handling.
This should solve both problems once and for all.
> Replaced the python version checks

- plugin.video.amazon-test/default.py
- plugin.video.amazon/resources/lib/common.py
- Fixes #91
- Reduces requests to primevideo.com servers
- Increases loading times (past the initial scraping and caching)
- Forbid the video data from expiring
- Single season series are now squashed: `Series name => Episode list` instead of `Series name => Season 1 => Episode list`
> Video data split from catalog cache

- plugin.video.amazon-test/default.py
- plugin.video.amazon-test/resources/language/resource.language.en_gb/strings.po
- plugin.video.amazon-test/resources/settings.xml
Forced subs (`ForcedNarratives` for PrimeVideo) are not shown in PrimeVideo player's subs selection menu, but they are selected by default with the corresponding audio track, e.g.:
They are retrieved alongside normal subs by getting `GetPlaybackResources` with `ForcedNarratives` as desired resource, and the result is stored in `forcedNarratives` list which has the same format of `subtitlesUrls` list (every element has `languageCode`, `displayName`, `url`, etc., keys).
They can be recognized by the word _"forced"_ in `displayName` key (just like [CC] subs).
To parse them properly I've appended `data['forcedNarratives']` list to `data['subtitlesUrls']` list for the subs parsing loop and I've added the suffix ".forced" to the matching subtitles' language code which is also appended to the …
> Added support for forced subtitles

- plugin.video.amazon-test/default.py
Sometimes Amazon, seemingly randomly, forgets the locale it's sending data with and returns descriptions, titles and dates in `en_US`. Applied a small fix that tries to decode dates as en_US before declaring an error.
> Fixed date parsing with incorrect locales

- plugin.video.amazon-test/default.py
- plugin.video.amazon-test/resources/language/resource.language.de_de/strings.po
- plugin.video.amazon-test/resources/language/resource.language.en_gb/strings.po
- plugin.video.amazon/resources/language/German/strings.po
Several improvements to subtitle handling and code readability (#113).
Adds support for the forced narrative subtitles, for the additional options from the Kodi `Player > Language > Subtitles` settings, and for the download of .srt files straight off amazon's servers (as hinted by @muphus).
> Forced subtitles support and .SRT download instead of .DFXP

- plugin.video.amazon-test/default.py
Slightly modified and renamed `setView` into `setContentAndView`. Kodi wasn't actually considering the PrimeVideo streams as videos because the content wasn't set as `videos` (actually wasn't set at all). This had the benefit of thumbnails instead of icons on the list view, but the hugely negative effect of not being tracked by Kodi and various other skin-specific behaviours.
@Sandmann79 can you confirm these changes don't impact amazon.tlds? I've looked up that portion of your code and since episodes are being passed as `episode` everything should work perfectly fine, but one can never be too sure.
> Watched functionality for PrimeVideo

- plugin.video.amazon-test/default.py
- plugin.video.amazon-test/resources/language/resource.language.de_de/strings.po
- plugin.video.amazon-test/resources/language/resource.language.en_gb/strings.po
Adds the enhancement needed from #105, where the user has no visual feedback of things going wrong during the request of territorial informations. The causes of @oomek's problems are still unknown.
> Add user notification on territorial error

- plugin.video.amazon-test/resources/lib/network.py
The re.sub() call on the following line would fail with an UnicodeDecodeError
if attempting to login with an account with non-ASCII characters in their
registered name.
> Fix Amazon VOD login for accounts with Unicode characters in name.

- plugin.video.amazon-test/resources/lib/network.py
- plugin.video.amazon-test/resources/lib/primevideo.py
Fixes #228
@Sandmann79 after being notified of timeout/retries errors, I noticed that a part of our network stack within `getURL` was a bit messy:
* it retried cluelessly, even when it should absolutely not retry (eg: 404s)
* when `check=True` it would still retry once
On top of fixing those two issues, inside 12da226a7343a37159a6170d157bb5fa737aa6d2 I also changed the following:
* added a queryable static variable inside `getURL`, that would allow some sort of informed decision to be taken based on what HTTP status code was received (`lastResponseCode` would also be 0 in case of non-HTTP errors, there's also the possibility to expand with custom errors)
* refactored the hack-ish retry exception throws by adding two proper custom exceptions, `TryAgain` and `NoRetries`: retry on `408 …
> Forbid retries on permanent errors

- plugin.video.amazon-test/resources/language/resource.language.en_gb/strings.po
- plugin.video.amazon-test/resources/lib/common.py
- plugin.video.amazon-test/resources/lib/network.py
- plugin.video.amazon-test/resources/lib/playback.py
- plugin.video.amazon-test/resources/lib/primevideo.py
- plugin.video.amazon-test/resources/lib/proxy.py
- plugin.video.amazon-test/resources/settings.xml
- plugin.video.amazon-test/service.py
Fixes #262
Fixes #264
Fixes #265
Introduces an HTTP only proxy service to be used with the Addon. Current features include language remapping for audio streams in MPDs and on-the-fly subtitle alteration (TTMLv2 => SRT). With this method we also don't need to pre-download subtitles anymore.
To fix some of the language selection problems, I also suppressed locale information when only one language code is available, for example:
* `es-es` and `es-419` are available, the former becomes `es`, the latter `es-Latinoamerica`
* `es-419` is available, becomes `es`
After the suggestion of @Paco8 I also introduced an option that provides a time stretched variant (slightly slower) of the subtitles, to fix some of the sync problems with the Spanish ones.
> Add proxy service

- plugin.video.amazon-test/service.py
> 2019-03-02 10:54:10.736 T:3791369072 ERROR: EXCEPTION Thrown (PythonToCppException) : > -->Python callback/script returned the following error<--
> - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.NameError'>
Error Contents: global name 'export_watchlist' is not defined
Traceback (most recent call last):
File "/storage/.kodi/addons/plugin.video.amazon-test/service.py", line 69, in <module>
BackgroundService().run()
File "/storage/.kodi/addons/plugin.video.amazon-test/service.py", line 51, in run
export_watchlist(ct)
NameError: global name 'export_watchlist' is not defined
-->End of Python script error report<-- 
https://www.kodinerds.net/index.php/Thread/44211-Release-Amazon-Prime-Instant-Video/?postID=515637#post515637
> [Amazon VOD] Fix: Watchlist export

- plugin.video.amazon-test/resources/lib/network.py
This forces SD videos, which are not related to VMP
Tested with:
- Raspberry Pi 3 - LibreELEC 9.0.1 -> Hanna S01E01 -> **SD**
- MacBook Pro - macOS 10.13 -> Hanna S01E01 -> **SD**
- Mi Box S - androidtv 8.1 ->  Hanna S01E01 -> **HD**
> [Amazon VOD] Fix video playback (related to #293 #294)

- .github/ISSUE_TEMPLATE/config.yml
config.yml not is working as excepted due missing "about" tag.
See screenshot after the change
Maybe the text of German Forum should be in German?
> Add about tag to config.yml

- plugin.video.amazon-test/resources/lib/playback.py
I didn't test it, but I think this should fix the problem with 'inputstreamaddon' being deprecated in Kodi 19. See https://github.com/xbmc/xbmc/pull/18002
> Fix inputstreamaddon Kodi 19 incompatibility

- plugin.video.amazon-test/resources/lib/network.py
Exception was being raised due to mechanical soup looking for the input name and not id which prevented login.
> change from field id for captcha to field name

- plugin.video.amazon-test/resources/language/resource.language.de_de/strings.po
- plugin.video.amazon-test/resources/language/resource.language.en_gb/strings.po
- plugin.video.amazon-test/resources/language/resource.language.es_es/strings.po
- plugin.video.amazon-test/resources/language/resource.language.fr_ca/strings.po
- plugin.video.amazon-test/resources/language/resource.language.he_il/strings.po
- plugin.video.amazon-test/resources/language/resource.language.it_it/strings.po
- plugin.video.amazon-test/resources/language/resource.language.pl_pl/strings.po
- plugin.video.amazon-test/resources/lib/common.py
- plugin.video.amazon-test/resources/lib/primevideo.py
- plugin.video.amazon-test/resources/settings.xml
Fixes #499
Supports cache expiry times of 1 hour, 6 hours, 12 hours, 1 day, 3 days, 7 days, 15 days, 30 days with default as 12 hours. Can configure in Settings -> Prime video.
Please let me know if you want me to add other language strings using Google translate. I can only speak English natively.
Also, any changes required in cache options? Should I add an option to disable cache also (Expiry time: 0 seconds)? 
I have tested in Raspberry Pi 3 on OSMC and it seems to work fine.
> Added setting to configure catalog cache expiration time

- plugin.video.amazon-test/resources/lib/network.py
I ran in the same problem as mentioned here: https://github.com/Sandmann79/xbmc/issues/540#issuecomment-772531015
A partial solution/workaround was provided in the next comment (installing a compat package), but that didn't work on my system (Gentoo Linux).
It seems that Python removed the default "accept all SSL/TLS versions" (through SSLContext.options) in version 3.7 and introduced SSLContext.minimum_version, which is set to TLSVersion.TLSv1_2 by default on my system.
The PR contains a check on the python version and sets SSLContext.minimum_version to the version as suggested in the link above. The compat package should not be required anymore to make this work.
> Lower minimum TLS version on Python 3.7 and higher for signing in.

- plugin.video.amazon-test/resources/lib/playback.py
Some content, like Amazon Freevee, is not available when using token auth. By allowing to use cookie auth if token auth does not work, it will be possible to play that content without degrading the quality of anything that is available with token auth.
Admittedly, just stuffing the code into a loop that iterates over `[True, False]` is a bit of a hack, but it seemed cleaner that just putting the code there a second time. I would have prefered a method, but given that the return values from `_getPlaybackVars` are used later, this could have become a bit messy. In a loop they will just "leak" to the outside, because of python.
> Use cookie auth if requesting the manifest fails with token auth

- plugin.program.browser.launcher/default.py
After Updating Kodi from 19 to 20 I received the following exception from plugin.program.browser.launcher:
```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'AttributeError'>
Error Contents: module 'xbmc' has no attribute 'translatePath'
Traceback (most recent call last):
File "/home/kodi/.kodi/addons/plugin.program.browser.launcher/default.py", line 23, in <module>
customPath = xbmc.translatePath(addon.getSetting("customPath"))
AttributeError: module 'xbmc' has no attribute 'translatePath'
-->End of Python script error report<--
```
The proposed changes fixes browser.launcher to work with Kodi 20.
Please have a look when time permits. Thank you!
> Kodi 20 compability for browser launcher

- plugin.video.amazon-test/resources/lib/android_api.py
When fetching season fanart via `android_api`, the operation failed causing repeated error messages and logs:
```
2023-10-01 17:56:39.613 T:5987     info <general>: [Amazon VOD] Starting Fanart Update
2023-10-01 17:56:39.626 T:5987     info <general>: [Amazon VOD] getURL: https://atv-ps-eu.amazon.de/cdp/mobile/getDataByTransform/v1/android/atf/v3.jstl?deviceTypeID=A43PXU4ZN2AL1&firmware=fmw:22-app:3.0.351.3955&softwareVersion=351&priorityLevel=2&format=json&featureScheme=mobile-android-features-v11&deviceID=7b6356e9d478429f86124f2de6d84fbc&version=1&screenWidth=sw800dp&osLocale=de_DE&uxLocale=de_DE&supportsPKMZ=false&isLiveEventsV2OverrideEnabled=true&swiftPriorityLevel=critical&itemId=amzn1.dv.gti.9aaffebb-576e-d355-a2d4-9ed14731e7ab&capabilities=
2023-10-01 17:56:39.895 T:5987    error …
```
> Fix broken fetch of season fanart

- plugin.video.amazon-test/resources/lib/network.py
If fixed this on my kodi installation by iterating over siteWide->bodyStart and pick the one with name navigation-bar instead of always the first.
Please kindly review and if it meets your standards merge this change to get this sorted out for other users of this addon.
fixes #749 , fixes #750
> Fix for changed navigation structure

- plugin.video.amazon-test/resources/lib/playback.py
This change addresses #753 for OSMC 2024.05-1 and Kodi 20.5 on Raspberry Pi 4.
> [playback] restore manifest_type property for version of Kodi prior to 21
